### PR TITLE
[WhoReacted]Update 'Reactions' module to renamed 'MessageReactions'

### PR DESCRIPTION
**Pull request by x04ty29er**
This should hopefully address https://github.com/jaimeadf/BetterDiscordPlugins/issues/361
It looks like the 'Reactions' module got renamed to 'MessageReactions'
Simple change to rename the module that is searched for.

Let me know if process wasn't followed or if other changes are needed.

### CODE REVIEW

**Comment by merri1400** [comment]
So I feel dumb because the plugin won't compile at the start and it doesn't let me get to that line to change it, it's only a few lines. How do I get that far down in the module?

**Comment by Firecul** [comment]
Thanks, that seems to work

**Comment by medovanx** [comment]
this works, thank you

**Comment by mkwsnyder** [comment]
+1 for this solves the issue

**Comment by x04ty29er** [comment]
Rebase against develop and removed the change to files in dist. For those manually patching from this PR, it no longer contains the js changes as the contribution instructions (that I forgot to read. Sorry!) indicate not to check in built files. You can still manually patch by either examining the earlier commit, or just making the equivalent change to the JS.

**Comment by x04ty29er** [comment]
Looks like develop branch was updated with a different solution. Closing this PR.

**Comment by jaimeadf** [comment]
Hey, thanks for fixing the issue in the meanwhile. I've not used your solution as the fix because `MessageReactions` is the modal component and served only as the intermediary to get the `Reaction` component. Now, I found a more straightforward way to find it directly.

**Comment by x04ty29er** [comment]
Seems good to me. Documentation was pretty hard to find, so I stopped reversing once I had something that kind of worked in place. Your fix seems like it's a better fix anyway. 👍

**Pull request closed without merging**
