### PR TITLE
fix(BiggerStreamPreview): broken context menus

### PR DESCRIPTION
**Pull request by LoSunny**
With reference to [Strencher's PronounDB](https://github.com/Strencher/BetterDiscordStuff/blob/development/PronounDB/index.js#L142-L200)

### CODE REVIEW

**Comment by jaimeadf** [comment]
It isn't working for me. I get this error when I try to open a user menu.
image

**Comment by LoSunny** [comment]
Which version are u using? I'm using
```
Stable 121601 (c130b44)
BetterDiscord 1.5.2
Host 0.0.266 OS X 10.15.7 (19.6.0)
OS X 10.15.7 (19.6.0)
ZeresPluginLibrary 2.0.2
```

**Comment by jaimeadf** [comment]
```
Stable 121719 (faa867d)
BetterDiscord 1.5.2
Host 1.0.9004 Windows 10 64-Bit (10.0.22000)
```

**Comment by jaimeadf** [comment]
Oops, clicked the wrong button.

**Comment by LoSunny** [comment]
I have created a virtual Windows machine and verify that it should be working now.
Moreover I have removed the "patchStreamContextMenu" as it seems that discord had removed that webpack module
FYI
```
Stable 122087 (5c6d04c)
BetterDiscord 1.5.2
Host 1.0.9004
Windows 10 64-Bit (10.0.19041)
```

**Comment by jaimeadf** [comment]
Some discord modules are lazy loaded now, including the context menus, which is the reason why it doesn't appear for you. Can you revert that change, please? I can get it working.

**Comment by LoSunny** [comment]
I have reverted the changes, but as the method `pushStreamPreviewMenuItems` has one more argument, I'm not sure will the code works or not

**Comment by jaimeadf** [comment]
Thanks, I'll do some testing now and make it work for the other menu.

**Pull request merged**
